### ISSUE TITLE
Translations do not work while Bee-Better is installed.

### ISSUE THREAD

**Issue by Neonis00** [P03W/RPGStats#101]
**Describe the bug**
When RPGStats is installed alongside Bee Better, the '/rpgstats' output is not translated and is shown as raw strings.

**To Reproduce**
1. Install Bee-Better and RPGStats together.
2. Type '/rpgstats' command.
3. See bug

**Expected behavior**
The '/rpgstats' command should show translated text.

**Screenshots and Logs**
Bee-Better w/ RPGStats:
![image](https://user-images.githubusercontent.com/47197231/161735079-7c787e1b-e65f-44d0-814b-88d5567f9cd6.png)

Expected result for RPGStats:
![image](https://user-images.githubusercontent.com/47197231/161736191-37262268-2bf7-49c6-b2e6-0c7ea0ab4dbc.png)

**Environment**
- [ x ] Server
- [ x ] Client

**Mod list**
Mod that causes the issue: 
Bee-Better: https://github.com/Draylar/bee-better

Other mods installed:

![image](https://user-images.githubusercontent.com/47197231/161739725-42b7b69c-d541-4b11-89ea-884885f16b81.png)
![image](https://user-images.githubusercontent.com/47197231/161739742-a679f277-ebc8-4e32-9e49-01e3899051fb.png)
![image](https://user-images.githubusercontent.com/47197231/161739754-13fc6818-12bd-4678-8f9d-ffbb38e0271e.png)

**Comment by P03W** [comment]
Could you check if this is fixed when https://github.com/Draylar/maybe-data/releases/tag/1.3.0-1.18.2 is present in the mods folder?

**Comment by P03W** [comment]
Should be fixed in 4.3.11
