### ISSUE TITLE
Melee damage bug

### ISSUE THREAD

**Issue by bi1134** [P03W/RPGStats#102]
i'm using minecraft 1.16.5 and when my melee exp bout to level up, me and my friends are killing a mob. When its almost reached to lv1, i died and im respawn with lv50 melee and 19~20XP, later on 1 of my friend also got the same but doesn't have XP and my other friend got lv10 melee instead of 1 or 50
I'm also having playerEX with it

**Comment by chronosacaria** [comment]
Could you please me more specific? What version are you using? What other mods do you have? Are you on a Server? There is so little information that you have provided so there really isn't a lot to go on for testing here. Please use the Bug Report Template for future issues

**Comment by bi1134** [comment]
> 

im using 1.16.5

**Comment by bi1134** [comment]
[https://drive.google.com/file/d/16LkrYktG-WCC0xcKPpIZtaTFi9NJDmbS/view?usp=sharing](url) this is my full modpack

**Comment by chronosacaria** [comment]
Can you provide a list of your mods, please @bi1134? I am not keen on downloading something off of someone's Google Drive

**Comment by P03W** [comment]
Alright its been 2/3 of a month, I dont think were getting anything

If someone else can reproduce this feel free to comment or open a new issue
