### ISSUE TITLE
Relicensing RPGStats to MPL-2.0

### ISSUE THREAD

**Issue by P03W** [P03W/RPGStats#103]
I'm hoping to relicense this mod to [MPL-2.0](https://www.mozilla.org/en-US/MPL/2.0/). This repo was originally licensed as CC-0 as it was just a quick throwaway mod for a modfest. However as I've invested more time and effort into this mod, and other people have contributed fixes, translations, content, ect (❤️) I don't believe that contributing it straight to the public domain makes much sense now.

I commonly use the MPL-2.0 on my other projects because I appreciate the protective features it has while not being overly restrictive, protecting mainly existing files and not require projects linking to relicense. However, people still own the copyright of their individual contributions, so I need your permission!

Please comment your approval for this relicensing or state why you disagree, I want to make sure everyone is happy with this change.

- [x] @P03W
- [x] @trobol 
- [x] @koelle25 
- [x] @TheMisteryMan 
- [x] @Katorone 
- [x] @LordDeatHunter 
- [x] @chronosacaria 
- [x] @semper-idem 
- [x] @Kluzzio

**Comment by koelle25** [comment]
I'm fine with it! :)

**Comment by semper-idem** [comment]
Agreed

**Comment by LordDeatHunter** [comment]
It's a go from me 👍

**Comment by chronosacaria** [comment]
I'm game for that 👍

**Comment by trobol** [comment]
great idea, fully agree

**Comment by TheMisteryMan** [comment]
Seems reasonable enough to me. I'm okay with it. +1

**Comment by Kluzzio** [comment]
Yep, sorry for the delay

**Comment by Katorone** [comment]
No objections at all!

**Comment by P03W** [comment]
Alright thanks everyone! :D
