### ISSUE TITLE
[Crash] Server tick loop

### ISSUE THREAD

**Issue by itsdinkd** [P03W/RPGStats#104]
**Describe the bug**
Official server to Another Quality Modpack 2 keeps crashing, looking at the logs for just today there is over 5 crash logs all with the same output as below

**To Reproduce**
1. I unfortunately cannot say reproduction steps as I am just getting told its crashing a lot

**Environment**
- [X] Server
- [ ] Client
- [ ] Singleplayer
- [ ] Lan Server

**Crash Log**
https://pastebin.com/0Nv3Fi2s

**Comment by P03W** [comment]
well this is.... bizzare

**Comment by P03W** [comment]
What the hell, how is this only popping up now??

**Comment by itsdinkd** [comment]
Looks like its been happening for a few days now, I am just now noticing it. is it a server side fix? if so, I can replace my servers version, otherwise I would have to update the whole modpack and send it out

**Comment by P03W** [comment]
Should be a server side fix

**Comment by P03W** [comment]
The confusion is that *everyone* should be dealing with this crash, and this feature has existed for like, months
