### ISSUE TITLE
2.2.0+1.16.2 Server crash

### ISSUE THREAD

**Issue by Katorone** [P03W/RPGStats#12]
[latest.log](https://github.com/P03W/RPGStats/files/5123652/latest.log)

**Comment by P03W** [comment]
`java.lang.ClassNotFoundException: net.minecraft.util.registry.Registry`

This is a bit terrifying, `Registry` is a core minecraft class, it shouldnt not exist

**Comment by Katorone** [comment]
I've seen this in another mod, where the -dev version got uploaded accidentally. (the exact same reference to Registry)

**Comment by P03W** [comment]
Not what happened though, file name on curseforge and github is correct

**Comment by P03W** [comment]
Can you reproduce this issue on 2.2.1?

**Comment by Katorone** [comment]
Trying now, will post an update.

**Comment by Katorone** [comment]
2.2.1 on both client and server.  No crashes, and the client can join the server just fine.
Thanks a lot!

**Comment by P03W** [comment]
NP, happy to help
