### ISSUE TITLE
2.2.0+1.16.2 Client crash

### ISSUE THREAD

**Issue by Katorone** [P03W/RPGStats#13]
Even though the log says -server, it's generated by a client crashing.
This might be related to the server crash I posted earlier, I created a 2nd issue because the log seems different.
[crash-2020-08-25_15.02.45-server.txt](https://github.com/P03W/RPGStats/files/5123879/crash-2020-08-25_15.02.45-server.txt)

**Comment by Katorone** [comment]
Did you accidentally upload a wrong version?
![image](https://user-images.githubusercontent.com/918422/91178025-d9d88880-e6e4-11ea-8106-67209f3746a0.png)

**Comment by P03W** [comment]
The 16 hours old one should be deleted, CF mustve messed up (Deleted now)

Issue is fixed in 2.2.1 though, I forgot static values still have an init order, so thats fixed
