### ISSUE TITLE
rpgstats-2.1.4+1.16.1.jar crashes on 1.16.1

### ISSUE THREAD

**Issue by calloatti** [P03W/RPGStats#14]
https://paste.ee/p/Cix9P

rpgstats-2.1.4+1.16.1.jar

cardinal components used is for 1.16.2

**Comment by InsaanNotFound** [comment]
Same problem here

**Comment by P03W** [comment]
Sorry about that, I forgot CCA wasn't version independent

**Comment by InsaanNotFound** [comment]
Any chance for a fix?

**Comment by P03W** [comment]
Oh yes absolutely
Should be out by the end of the day

**Comment by InsaanNotFound** [comment]
Good to hear it!

**Comment by P03W** [comment]
2.1.5+1.16.1 reverts the CCA changes, seems to work

Sorry for the inconvenience!

**Comment by InsaanNotFound** [comment]
I confirm that newest update fixed it.

**Comment by P03W** [comment]
That's very odd, it works in dev
Are you sure it's not another mod packaging another version of CCA or something?

Crash log would be appreciated

**Comment by calloatti** [comment]
https://paste.ee/p/38I4q

![](https://user-images.githubusercontent.com/12817862/92174863-bf07c180-ee12-11ea-8033-c46c161c5e81.png)

![](https://user-images.githubusercontent.com/12817862/92174935-c3cc7580-ee12-11ea-8ca7-71fa4294bb58.png)

**Comment by P03W** [comment]
Seems to be an incompatibility with INMIS
the issue seems to be RPGStats is including 2.5.0 of CCA while INMIS includes 2.4.0

RPGStats seems to run fine on 2.4.0 though, so ill can update/downgrade it to use 2.4.0

**Comment by P03W** [comment]
backport-2.3.1 includes 2.4.0 instead
