### ISSUE TITLE
Fishing Stat Gets Reset After Respawn

### ISSUE THREAD

**Issue by IAmSneak** [P03W/RPGStats#15]

**Comment by P03W** [comment]
This sounds like a deeper issue, all stats are stored the same, if one goes missing all should

Please supply

1. Mod list
2. Game version
3. Log file

**Comment by IAmSneak** [comment]
Game version: 1.16.2
Very Long Mod List
No Log File

I looked into the code and saw that "EntityComponents.setRespawnCopyStrategy(FISHING_COMPONENT, RespawnCopyStrategy.ALWAYS_COPY);" is missing from main/RPGStats.java

It is not on server restart (as I was assuming) and instead on respawn.

**Comment by P03W** [comment]
Thanks, this sure is odd, I thought for sure I put all the important stuff in registerSkill, guess not

Will be fixed in next version
