### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by Moglibogli** [P03W/RPGStats#18]
i dont know how many times this has happened but it seems that each time i stop and restart the server all the stats reset

**Comment by P03W** [comment]
That shouldn't be happening as its stored with player data. Would you mind sending a log (and a player data file if possible?)

**Comment by Moglibogli** [comment]
im not sure where that would be stored. also i think it may have only happened once or twice but the stats are still there but they arent the ones being used. like they are in the gui but the ones being used were reset.

**Comment by P03W** [comment]
I'm not sure I quite understand the behavior your describing, what do you mean by "being used"?

**Comment by Moglibogli** [comment]
i mean that they show up in the gui but when i do /rpgstats the values have been reset

**Comment by P03W** [comment]
Those are using the same set of data so that shouldn't be able to happen, ill look into it

**Comment by P03W** [comment]
Yep these bits are almost exactly the same, could you send screenshots of this and a log?

**Comment by P03W** [comment]
Any update on this @Moglibogli ?

**Comment by P03W** [comment]
I'm going to assume this is a non-issue due to your lack of response

If this is an actual issue please comment with the requested materials
