### ISSUE TITLE
suggestion - enhancement: keep on death

### ISSUE THREAD

**Issue by superon** [P03W/RPGStats#19]
could we have the option to keep stats on death rather than have them reset to zero? i think that'd be grand

**Comment by P03W** [comment]
They *shouldn't* be resetting to 0 on death, do you have a log or anything?

I expect this has come up from upgrading CCA but I'll be highly annoyed if that is the cause

**Comment by superon** [comment]
from what i can tell there's not a lot to see, i oft can't tell though so here you go:
https://pastebin.com/juSDwJJx

**Comment by superon** [comment]
fabric-api-0.29.0+1.16
rpgstats-3.0.3+1.16.4

**Comment by P03W** [comment]
Does 3.0.4 resolve the issue?

**Comment by superon** [comment]
seems so, thanklies :)  how about having an option to have them reset on death too :P

**Comment by P03W** [comment]
Sure, ill add a "hardcore" option lol

Making a new issue for that

**Comment by PassyFox** [comment]
is it possible to make it togglable that all the curent xp gets reset but the levels remain, or even have a small config you can put in to set the amount of levels or xp lost on death?
