### ISSUE TITLE
Sugestion - Collor player names based on role

### ISSUE THREAD

**Issue by PassyFox** [P03W/RPGStats#21]
Give each player highest stat a different colour to their name, so when their magic is the highest level, their name turns purple in the playerlist (for example)

**Comment by P03W** [comment]
Ill likely do this by properly implementing advancement criterions, so you can build your own advancements that run functions and grant the colors

**Comment by P03W** [comment]
This will be doable in the next release, for example creating an advancement with a criterion of

```
"criteria": {
    "levelup": {
      "trigger": "rpgstats:player_level",
      "conditions": {
        "stat": "rpgstats:defence",
        "level": 5
      }
    }
  }
```

will fire when the player reaches defence lv 5 (also "rpgstats:_any" for any stat)
