### ISSUE TITLE
Sugestion - Make a Cofig file to set values

### ISSUE THREAD

**Issue by PassyFox** [P03W/RPGStats#22]
have the mod create a config file being placed in the config folder of fabric, which you can edit and set the values of gained xp per event or needed for each level for further finetuning as to per server needs

**Comment by P03W** [comment]
Theres already a basic level level scaling config, and more control is planned (see the `Projects` tab)

**Comment by PassyFox** [comment]
ohw where is that config file placed, maybe i'm just overlooking things

**Comment by P03W** [comment]
it should be `config/rpgstats.json5`

**Comment by P03W** [comment]
Mostly moot as of 4.0.0 rewrite
