### ISSUE TITLE
Bug - GUI not working

### ISSUE THREAD

**Issue by PassyFox** [P03W/RPGStats#24]
when the server and the client have it installed the client crashes

**Comment by P03W** [comment]
Please provide a crash report instead of a vague, unhelpful message

**Comment by PassyFox** [comment]
![error](https://user-images.githubusercontent.com/20614880/104624681-26246500-5694-11eb-9e98-721ac71c33f0.png)

included with the mods installed on the client

**Comment by P03W** [comment]
Install fabric api
