### ISSUE TITLE
Incomplete Wiki

### ISSUE THREAD

**Issue by PassyFox** [P03W/RPGStats#26]
we notice on the server that not only on the 25th and 50th level give extra buffs, is it possible to fill out the rest of the buffs?

**Comment by P03W** [comment]
Do you mean the per-level buffs? Those are fully documented as far as I'm aware, just above the divider

**Comment by PassyFox** [comment]
![Screenshot](https://user-images.githubusercontent.com/20614880/104816599-8ba35d80-581c-11eb-9fef-6a76043e1cc4.png)

it only lists the lvl 25 and lvl 50 perks, but you get extra hearts at some levels, also you get like bonemeal accuarcy at cerntain levels, extra knockback resistance and sow fort

**Comment by P03W** [comment]
Oh I see, ill fix up the wiki, thanks

**Comment by P03W** [comment]
Wiki should be up to date now
