### ISSUE TITLE
Bug - defender being based of normal damage

### ISSUE THREAD

**Issue by PassyFox** [P03W/RPGStats#28]
it seems when people jump of a high cliff and survive the fall they gather xp, i thought the modifier for defender was shield damage blocked and not all the damage a person takes?

**Comment by P03W** [comment]
Theres a recent small addition of xp for armor and enchants blocking damage, added to wiki

**Comment by PassyFox** [comment]
but then this is way to overpowered, people are jumpin of towers just to bump up their defense stat, this should't be the idea behind this stat i think? shield block yes, but this is a but much

**Comment by P03W** [comment]
The formula is (damage / 2)^1.3 currently, ill switch it to log instead of pow so it caps at around 10

**Comment by P03W** [comment]
3.0.5 uses new formula (when curseforge approves, shouldn't be more than an half an hour or so, based on previous times)
