### ISSUE TITLE
Accessibility Option Request

### ISSUE THREAD

**Issue by Birgliss** [P03W/RPGStats#30]
Many mods (including yours) have the mechanic of "spam-sneak to rapidly grow crops."
However, for people with poorly-made hands like myself, we can't use this mechanic without chancing serious damage.
Is there any chance you could add an option for an alternate input? I would settle for a hold-sneak instead of a spam-sneak.

**Comment by P03W** [comment]
Absolutely, ill add that in the next update (shouldn't be more than 4days to a week)

**Comment by P03W** [comment]
Done, probably going to make a release now tbh, will be accessible with `/rpgstats toggleSetting spamSneak`

If you have any further suggestions or thoughts feel free to comment or open a new issue!
