### ISSUE TITLE
suggestion custom buffs

### ISSUE THREAD

**Issue by superon** [P03W/RPGStats#31]
this suggestion is brought to you because of the mining bonus at lvl 50.
in my pack i have a custom night vision effect which changes it to creeper vision.   that is because i want origins to handle the feline vision/ water vision differently. part of that mod is an unused "true_night_vision" effect...
aaanyway, if you could allow disabling these "bonus powers" or adjust the night vision to be a custom "lower light" vision or let us use custom effects/potion effects for lvl powers that'd be awesome too.

**Comment by superon** [comment]
or adding a toggle option for the night vision effect could be pretty nifty... though i realise this might be more specifically tailored to useful in my pack rather than generally :/

**Comment by P03W** [comment]
This is now possible in 3.2.0, you can disable the effects through the config and use a datapack to grant the custom effects
