### ISSUE TITLE
Game crash when loading 

### ISSUE THREAD

**Issue by CaptainFox2007** [P03W/RPGStats#34]
---- Minecraft Crash Report ----
// You're mean.

Time: 02/03/21 16:51
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'rpgstats'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/PacketSender
	at mc.rpgstats.main.RPGStatsClient.onInitializeClient(RPGStatsClient.java:26)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/networking/v1/PacketSender
	... 13 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.networking.v1.PacketSender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6142969472 bytes (5858 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		allure: Allure 1.2.8
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.12
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betternether: Better Nether 5.0.0
		biomemakeover: Biome Makeover 1.16.4-1.2.10
		blade: Blade 2.0.0
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.1.2
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-block: Cardinal Components API (blocks) 2.6.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		cardinal-components-level: Cardinal Components API (world saves) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 0.1.0-beta
		continuebutton: Continue Button 1.0.2
		cpas: conveniently placed armor slots 1.0.1+1.16.4
		dankstorage: Dank Storage 1.9a-1.16.3
		dragonloot: DragonLoot 1.0.3
		dynamicfps: Dynamic FPS 1.2.1
		enchant_giver: Enchant Giver 1.0.2
		enhancement: Enhancement (Fabric) 0.5.5
		fabric: Fabric API 0.25.1+build.416-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b4623793a
		fabricloader: Fabric Loader 0.10.6+build.214
		fallflyinglib: FallFlyingLib 1.1.0
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		jankson: Jankson 3.0.1+j1.2.0
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
		libblockattributes_items: LibBlockAttributes (Items) 0.8.4
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		magna: Magna 1.4.3-1.16.2
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		mambience: MAmbience 2.1.0+1.16.4
		maybe-data: Maybe data 1.0.0-1.16.2
		mcdw: MC Dungeons Weapons 2.6.0
		minecraft: Minecraft 1.16.4
		minihud: MiniHUD 0.19.0-dev.20201103.184029
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 1.14.13+build.19
		optifabric: OptiFabric 1.8.13
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		origins: Origins 0.4.7
		patchouli: Patchouli 1.16.2-44-FABRIC
		piglib: Piglib 1.0.1
		plantinajar: Plant In A Jar 1.8.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		replaymod: Replay Mod 1.16.4-2.5.2
		ringsofascension: Rings of Ascension 1.0.7
		roughlyenoughitems: Roughly Enough Items 5.8.1
		roughlyenoughitems-api: REI (API) 5.8.1
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.1
		roughlyenoughitems-runtime: REI (Runtime) 5.8.1
		rpgstats: RPGStats 3.2.1+1.16.4
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		supernaturalcrops: Supernatural Crops 1.0.2
		team_reborn_energy: Energy 0.1.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trinkets: Trinkets 2.6.7
		voxelmap: VoxelMap 1.10.11
		waila: Hwyla 1.9.22
		worldedit: WorldEdit 7.2.0+a51fa43
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.10.6+build.214-1.16.4
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.4
	OptiFine jar version: OptiFine_1.16.4_HD_U_G5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: /Users/archiesalsbury/Library/Application Support/minecraft/.optifine/OptiFine_1.16.4_HD_U_G5/Optifine-mapped.jar
	OptiFabric error: <None>

that is the crash report.
the list of mods i am using are as follows:

fabric-api-0.25.1+build.416-1.16.jar
RoughlyEnoughItems-5.8.1.jar
Better-Nether-Mod-Fabric-1.16.4.jar
fabricmod_VoxelMap-1.10.11_for_1.16.3.jar
fabric-language-kotlin-1.4.0+build.1.jar
continuebutton-1.0.2.jar
dynamic-fps-1.2.1.jar
byg-1.1.2.jar
shulkerboxtooltip-2.3.3+1.16.4.jar
conjuring-0.1.0-beta.jar
cpas-1.0.1+1.16.4.jar
worldedit-fabric-mc1.16.3-7.2.0-dist.jar
appliedenergistics2-fabric-8.1.0-alpha.12.jar
astromine-1.11.4+fabric-1.16.3.jar
dankstorage-1.9a-1.16.3.jar
supernatural-crops-1.0.2.jar
dragonloot-1.0.3.jar
plantinajar-1.8.1.jar
modmenu-1.14.13+build.19.jar
minihud-fabric-1.16.4-0.19.0-dev.20201103.184029.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
OptiFine_1.16.4_HD_U_G5.jar
optifabric-1.8.13.jar
trinkets-2.6.7.jar
RingsOfAscension-1.16.3-1.0.7.jar
bunch-o-trinkets-1.0.1.jar
biome-makeover-1.16.4-1.2.10.jar
mcdw-2.6.0.jar
Allure-1.2.8.jar
enhancement-fabric-0.5.5.jar
inventoryprofiles-forge-1.16.2-0.4.2.jar
replaymod-1.16.4-2.5.2.jar
Hwyla-fabric-1.16.2-1.9.23-79.jar
Origins-1.16.5-0.4.7.jar
rpgstats-3.2.1+1.16.4.jar
Mambience-2.1.0+1.16.4.jar

**Comment by P03W** [comment]
You are using an outdated version of fabric api, update that

**Comment by CaptainFox2007** [comment]
that has not worked it still crashes

**Comment by P03W** [comment]
What's your fabric api version now?
