### ISSUE TITLE
[Bug/Idea] Compatibility with SimpleHarvest

### ISSUE THREAD

**Issue by Akorian** [P03W/RPGStats#35]
I have this mod on my server installed together with [Simple Harvest](https://www.curseforge.com/minecraft/mc-mods/simpleharvest). And players are reporting, that they don't get XP awarded for farming crops when they use the right-click functionality of Simple Harvest. It would be amazing if the mods could work better together.

**Comment by P03W** [comment]
Next version will have compatibility (3.2.2)
