### ISSUE TITLE
Farming level 25 ability not working

### ISSUE THREAD

**Issue by GoldenBlaze** [P03W/RPGStats#36]
I just got to level 25 in farming in my Minecraft survival server that I am running on my machine. I noticed that when I attempt to use the level 25 ability from framing that nothing happens. There is no growth speed increase nor is there any indication that anything is happening. I tested to make sure it wasn't the server's fault so I went into a single-player world and tested it. No change.

I then tested this again in a standalone game with ONLY Rpgstats installed and fabric API. Still no change.

Tested with wheat and sugarcane.

**Comment by P03W** [comment]
Does 3.2.0 work?

**Comment by GoldenBlaze** [comment]
I just tested it on the latest version. I was using 3.2.1. Then tested it with 3.2.2. Does not work.

**Comment by P03W** [comment]
Does it work before 3.2.0

**Comment by GoldenBlaze** [comment]
Deleted config and world. Made new world with 3.1.1. Tested with wheat and does not work. 

I am going to make sure I am doing it right. I am trying both spamming shift and holding shift. Neither do anything.

**Comment by GoldenBlaze** [comment]
The fabric API seems to have updated recently as well. I am currently using 0.31.0. Should I try another version?

**Comment by P03W** [comment]
Its unlikely to be fabric api

Are you holding a hoe while testing

**Comment by GoldenBlaze** [comment]
No I was not. The wiki did not say you needed a hoe.

**Comment by P03W** [comment]
Ill update the wiki, appologies

**Comment by GoldenBlaze** [comment]
I did want to know what crops this works on specifically. Because it does not work on sugarcane or netherwart.

**Comment by GoldenBlaze** [comment]
Ah ok. Question / request to add to wiki. What is the range of the 25 level and 50 level?

**Comment by P03W** [comment]
3x3 and 5x5 if I remember correctly

**Comment by GoldenBlaze** [comment]
Sweet thanks
