### ISSUE TITLE
Stat bonuses resetting after returning to overworld from the end. 

### ISSUE THREAD

**Issue by Zyphexis** [P03W/RPGStats#37]
All attributes and effects gained from leveling are seemingly resetting after returning to the overworld from the end.

**Comment by GamyGamer** [comment]
Reporting this too

Interestingly stats go back to where it should be after dying, at least health ( before leaving end 40 hp, after leaving 20 hp and dying restore that value to 40 hp )

**Comment by P03W** [comment]
Seems to be the same bug as #6 

This is quite annoying and mojang doesn't seem to have any intention of fixing it so ill likely do some rewrites so its not as much of a pain to fix in the future

**Comment by P03W** [comment]
Could any of you confirm if 3.2.5 fixes this issue?

**Comment by GamyGamer** [comment]
Using 3.2.6, It looks like it has been fixed. From /attribute command it still keeps 40 but after leaving end player health is set to 20 (attribute is still 40), but that's a bug that I know it existed while I was playing on mods in 1.10.2

**Comment by P03W** [comment]
Alright, sounds like the core issue is resolved though
