### ISSUE TITLE
Server crashes with new version (3.2.3)

### ISSUE THREAD

**Issue by Akorian** [P03W/RPGStats#39]
The Server crashes while the server starts. It only happens with the new version of this mod. 
console output: https://pastebin.com/UmexKjsp

Server is running Fabric on 1.16.5 with a hecc lot of other mods

**Comment by P03W** [comment]
Looks like Harvest got updated, ill push a new version with a fixed mixin

**Comment by P03W** [comment]
Actually harvest hasn't updated, might just be a mixin issue outside of dev

**Comment by Akorian** [comment]
So I can't do anything bout it?

**Comment by P03W** [comment]
Im working on fixing it
