### ISSUE TITLE
[Request] Update GitHub releases for JitPack

### ISSUE THREAD

**Issue by TheMisteryMan** [P03W/RPGStats#43]
Since there isn't a Maven repository for this mod, I'm using JitPack to use it with my project. I currently have to point to a specific commit though, as the latest mod versions haven't been put onto your GitHub releases, so I can't make use of gradle settings to change the version, and instead have to find the correct commit to use.

**Comment by P03W** [comment]
Ah I wasn't aware anyone was pulling it

I can start tagging future releases again

**Comment by TheMisteryMan** [comment]
I only just started. I'm hoping to use it for a levelling system for an add-on mod I'm working on for Origins. Thanks

**Comment by P03W** [comment]
Ah, I'm actually planning on doing a rewrite in the future (maybe a week?) which should make things easier, so might want to wait for that

**Comment by TheMisteryMan** [comment]
Ah, OK. Thanks for the heads-up.

**Comment by P03W** [comment]
New version + tag is out

**Comment by TheMisteryMan** [comment]
Thanks. Not sure if this question fits here, but has anything changed for the API with the rewrite, and will there be documentation for the "data-driven everything"?

**Comment by P03W** [comment]
Ah right I forget to mention that, mist have been busy

Basically the entire API page is outdated now, I'll work on typing up a new version today

**Comment by P03W** [comment]
API page is updated now

**Comment by TheMisteryMan** [comment]
Awesome. Thanks! 👌
