### ISSUE TITLE
Incompatibility  found with extraorigins mod

### ISSUE THREAD

**Issue by Nagasena12** [P03W/RPGStats#46]
Hello. I was playing a custom modpack based on the origins mod and found an incompatibility. The RPGStats mod conflicts with the extraorigins mod and causes the player to lose 2 hearts from the total life at each log if he chooses the piglin origin. I am sure it is a conflict between these two mods since I created a modpack a few minutes ago with only the mod origins and extraorigins and their dependencies and the rpgstats (and the mod jumploaders). Piglin origin forces the player's maximum life to be 8 hearts (2 hearts less). For a conflict of some kind with the rpgstats at each login the player loses 2 hearts from the total maximum life (so the player has 8 hearts at the first login, 6 at the second, 4 at the third etc.). I really appreciate the RPGStats mod and I think it is potentially a must for any pack that is inspired by the RPG style, so I report this incompatibility hoping that it can be resolved.
(Note: I only found this bug for the piglin origin but it could also apply to other origins such as the inchlin which predict a reduction in overall life.)

**Comment by P03W** [comment]
What version are you using

**Comment by Nagasena12** [comment]
1.16.5

**Comment by P03W** [comment]
No I mean RPGStats version and extra origins version

And what origin it is

**Comment by Nagasena12** [comment]
rpgstats-4.0.0+1.16.5
extraorigins 1.16.5-1.7.0
Origin chosen: piglin form extraorigins

**Comment by P03W** [comment]
Closing in favor of #48
