### ISSUE TITLE
Max health issues

### ISSUE THREAD

**Issue by P03W** [P03W/RPGStats#48]
Im creating this issue because people keep opening new issues

Im aware their are problems and am working on fixing it, please stop opening new issues when there are (at the time of writing) 2-3 already open

**Comment by P03W** [comment]
Alright, since hopefully people will actually come here, does 4.0.1 fix these issues

**Comment by beiarii** [comment]
Tested on both Singleplayer & a Multiplayer server, hp works fine as intended! I'll also try it with the bonus health from RPGstat levels as i haven't gotten to that point yet.

**Comment by Nagasena12** [comment]
I also just tested it in singleplayer and now it works well(i am the guy of the piglin origin) . Thanks a lot for fixing the bug

**Comment by P03W** [comment]
Well no other complaints, so I'm going to assume this is resolved
