### ISSUE TITLE
QoL - Only make the farming perk work when crouching with a hoe equipped

### ISSUE THREAD

**Issue by Katorone** [P03W/RPGStats#5]
Love this mod!
Sneaking on grass can get tedious because of the farming skill's perk.  Would it be possible to allow players to toggle this perk by checking for an equipped item like a hoe?

Right now, sneaking on grass always bonemeals it, requiring some cleanup when the effect isn't wanted.

**Comment by P03W** [comment]
By grass do you mean `minecraft:grass` or `minecraft:grass_block`

Ill definitely look into adding a tool check though, thanks for the feedback!

**Comment by P03W** [comment]
Hoe requirement added in 2.0.2

**Comment by Katorone** [comment]
I meant the grass block.  Thank you for the addition!

**Comment by Katorone** [comment]
This is working perfectly, and even detects modded hoes (better nether).  Thank you very much!
