### ISSUE TITLE
Add config for changing maximum level

### ISSUE THREAD

**Issue by Robinsls** [P03W/RPGStats#51]
Hello! I am making a modpack for a small server im in and i was wondering if you could add a config to make there be more levels, it would be great to have a leader board or something and just give deminishing returns after 50

**Comment by P03W** [comment]
Yeah sure I can do that

Although diminishing returns isn't *super* viable, you'll have to replace the default rewards yourself. Make sure to check the [API Page](https://github.com/P03W/RPGStats/wiki/API) for how to do that

**Comment by Robinsls** [comment]
Holy shit! You respond quick!

**Comment by P03W** [comment]
I have desktop notifications and I'm working on a different project haha

**Comment by Robinsls** [comment]
Thats crazy! Thanks mate, and so would there be a way to change the returns after a certain level (I don't know how the code is just curious as that would work too?
Also thanks for your quick responses!

**Comment by Robinsls** [comment]
Like i don't know this program and i only know python but like an if or while statement that checks for if the level is above 50 for example or something idk

**Comment by Robinsls** [comment]
i don't know if thats doable in this program and im not expecting you to im just wondering if i could find a way to do that here

**Comment by P03W** [comment]
> Thanks mate, and so would there be a way to change the returns after a certain level

Currently not really, as rewards are linearly hard coded as you can see [here](https://github.com/P03W/RPGStats/blob/bf73b70ef3fd45d04061203d42cf07f1a3cd7278/src/main/java/mc/rpgstats/main/Events.java#L190).

However what you can do is create a custom mod that uses that event with your own code to grant XP, or (more compatible with a modpack) you could create an advancement for each level reward you want.

For example, [this advancement](https://github.com/P03W/RPGStats/blob/master/src/main/resources/data/rpgstats/advancements/farming_10.json) checks for farming level 10, and you could use the ` rewards` field on advancements to grant loot or run datapack functions when that level is reached (you'll want to look into [kubejs](https://kubejs.com/) for datapack management most likely)

**Comment by Robinsls** [comment]
That actually sounds great! I'll have to pass for now as i already am in over my head trying to figure things out here lol! Maybe after i do figure this stuff out ill be interested in that!

**Comment by Robinsls** [comment]
Sorry for the inconvience!

**Comment by P03W** [comment]
None at all

**Comment by Robinsls** [comment]
Should i open a different issue if i just need to figure out where to go to edit the gains from a level? Is there like a specific folder i should place the code lines you gave us in the API thing?

**Comment by Robinsls** [comment]
Nvm i think we good i just am blind myself so lol

**Comment by Robinsls** [comment]
Also there is something that works kinda just the opposite of what dimishing returns did! So i got it all good!

**Comment by P03W** [comment]
Alright, getting 4.0.3 out which should allow you to mess with the max level 🤞

**Comment by P03W** [comment]
Welp curseforge doesnt seem to like me rn, you can download from the github releases until curseforge gets its act together

**Comment by Robinsls** [comment]
So as a question as this is my first modpack i am making do you tinker with the API inside of the code or do you do that in minecraft?

**Comment by P03W** [comment]
You can do it with datapacks and the config file

**Comment by Robinsls** [comment]
hey, i was wondering what the config was to change how hard it is to level

**Comment by Robinsls** [comment]
@Comment("Default 2.05")
        public double power = 2.05;
Is this it?

**Comment by P03W** [comment]
The equation by default is `floor(level^power * scale) + base`, you can throw equation into [desmos](https://www.desmos.com/calculator) for an easy visualization of the XP curve

**Comment by Robinsls** [comment]
Ight, also im a little confused about editing the confi files im sorry for asking this but i cant save the edits i make to the config file and when i make a new file its a text file so do i have to find a way to turn that text document into a java file or is it good? I'm sorry!

**Comment by P03W** [comment]
The config file is run/config/rpgstats.json5
You change the values there and they will change in game

**Comment by Robinsls** [comment]
And does this mod have to run both client side and server side or just server side

**Comment by P03W** [comment]
Just server side, theres an *optional* partial client side implementation
