### ISSUE TITLE
What is the solution for Mo Enchantments?

### ISSUE THREAD

**Issue by Greg-J** [P03W/RPGStats#52]
Is this an issue that RPGstats should resolve, or an issue that Mo Enchantments should solve?

**Comment by P03W** [comment]
We both modify bow accuracy, and only 1 will apply at a time

So either the ranged accuracy boost from RPGStats works, or the marksman enchant works

Idk what the solution is it's small and doesn't matter much

**Comment by Greg-J** [comment]
Got it.

For what it's worth, the reason I submitted this ticket is there is a line in the log file that you recommend removing one of the mods.

**Comment by P03W** [comment]
Uhg did they change that? it used to say something about possible bugs

Might remove that then

**Comment by Greg-J** [comment]
Yeah, I get this warning:

```
- Mod 'RPGStats' (rpgstats) conflicts with any version of mod 'Mo'Enchantments' (moenchantments), but a matching version is present: 1.15.0!
	 - While this won't prevent you from starting the game, the developer(s) of 'RPGStats' (rpgstats) have found that version 1.15.0 of 'Mo'Enchantments' (moenchantments) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
```

**Comment by P03W** [comment]
Ew yeah its not *that* important

Will be removed next release
