### ISSUE TITLE
Rpg stats and tweakeroo

### ISSUE THREAD

**Issue by DistanceMC** [P03W/RPGStats#53]
If I have fast right click enabled in tweakeroo, and I right click a dirt block, Rpg stats counts all of those clicks towards the xp gain. I was able to gain around 10 lvls of farming in about 1.5s

**Comment by P03W** [comment]
...what exactly are you doing?

Farming XP is only granted on breaking plant blocks (and mature crops) as well as killing farming mobs

There is nothing about hoeing ground or placing dirt granting XP
