### ISSUE TITLE
Defense Skill Possible Bug

### ISSUE THREAD

**Issue by Omega-01** [P03W/RPGStats#6]
This might not actually be an issue, but whenever you get the +1 Health through the Defense skill, you lose it upon death.

**Comment by P03W** [comment]
Able to confirm this, also happens with the /attribute command

Heres the vanilla bug report https://bugs.mojang.com/browse/MC-179940

Ill try to make a patch, which should hopefully automatically update your stats

**Comment by P03W** [comment]
Oops, forgot to close this, 2.0.3 fixes this issue
