### ISSUE TITLE
Stats display screen has one stat cut off

### ISSUE THREAD

**Issue by Limkanimka** [P03W/RPGStats#61]
1. The screen that shows your current levels does not show fishing, it can only be seen with the command /rpgstats
2. You can break and put back ancient debris and thus easily farm mining lvl

**Comment by P03W** [comment]
1. Ill look into it
2. I cant do anything about that

**Comment by P03W** [comment]
Looks like a LibGui issue I cant do anything about

Ill upgrade it but its really on them to resolve it

**Comment by P03W** [comment]
Possibly related to CottonMC/LibGui#114 ?

Its happening on my windows environment but worth a look I suppose

**Comment by semper-idem** [comment]
I forked this mod just to fix this but end up changing little bit more, feel free to look and yoink. 
Reason why you don't see last stat is cause you place every `StatEntry` at y:18 eg.
`this.add(name, 0, 18, 5*18,18);`
This makes all of them move 18 units down but scrollbar doesn't adjust for it so you can't scroll to it.
At least thats how I understand it

[https://github.com/semper-idem/RPGStats/blob/master/src/main/java/mc/rpgstats/client/screen/RPGStatDisplayGUI.java](url)

**Comment by P03W** [comment]
Do you mind PRing this? Thanks
