### ISSUE TITLE
Drinking potion doesn't grant Magic xp

### ISSUE THREAD

**Issue by Neubulae** [P03W/RPGStats#62]

**Comment by P03W** [comment]
What type of potion specifically? Any?

**Comment by Neubulae** [comment]
any potion. And more specifically, potion has to be sprayed directly on you to add XP. This makes leveling exceptionally hard

**Comment by P03W** [comment]
Nevermind, apparently I somehow never implemented that

Not sure how that happened

**Comment by Neubulae** [comment]
:facepalm:

**Comment by Neubulae** [comment]
Only collision counts sounds very concern to me

**Comment by P03W** [comment]
Yeah I'll fix it later today, thanks for bringing this up

**Comment by Neubulae** [comment]
:ok_hand:
