### ISSUE TITLE
Ranged xp

### ISSUE THREAD

**Issue by Limkanimka** [P03W/RPGStats#64]

**Comment by P03W** [comment]
Please provide an actual issue that needs fixing @Limkanimka

**Comment by Limkanimka** [comment]
“ The ranged stat is based on killing enemies with projectiles.

You gain 1xp for most mob kills, however the Ender Dragon and the Wither both give 130xp” 

Cannot be killed with a bow after 50% health

**Comment by P03W** [comment]
I wont be fixing this as mods could enable or disable this theoretically, and I want this to work as expected automatically
