### ISSUE TITLE
Magic Potion Duration Bugged (maybe?) / Proportional Bonus Duration

### ISSUE THREAD

**Issue by arf88** [P03W/RPGStats#66]
It might be, that it saying '+1 Potion Duration' doesn't actually mean an extra second to the potion, but it does seem weird that level 50 only gives a couple extra seconds to the duration. 

Regardless, having a flat add to the duration is biased for enhanced (glowstone) potions. A couple seconds more to a 8:00 Speed I potion isnt nearly as good as a couple seconds more to a :22 Regeneration II potion. Maybe the potion duration bonus should be proportional?

**To Reproduce**
Steps to reproduce the (maybe?) bug:
1. Enter world, no previous character data. Server (with and without mod on client-side) and Singleplayer had same result while testing
2. As Player run /rpgcheat Player rpgstats:magic set levels 50
3. Get a potion, note original duration
4. Drink, immediately check received effect's duration. It should give about 5 seconds bonus

**Environment**
- [X] Server
- [ ] Client
- [X] Singleplayer
- [ ] Lan Server

**Comment by P03W** [comment]
Thanks for catching this! Looks like I accidentally only made it add 2 ticks instead of 20 (1 second)

No comment on proportional duration at this point, I'll have to think on it
