### ISSUE TITLE
Mining Level-up Reward

### ISSUE THREAD

**Issue by g-Vost** [P03W/RPGStats#67]
I've been searching before about how the generic.luck attribute affects loot tables, and there's consensus that luck doesn't affect much. generic.luck uses a loot roll's bonus_roll stat and an item entry's quality stat. It seems the only loot table in the game that uses either is the fishing one, so it seems like an unfit per-level perk for Mining. Maybe something like increased block damage would be a good fit?

**Comment by P03W** [comment]
Unless someone else has a better idea, ive ultimately decided im going to implement increased mining speed, and remove the haste from lv50, so that will be coming eventually

**Comment by P03W** [comment]
Changed in 4.3.0

**Comment by PassyFox** [comment]
is it possible to put the changes in the wiki to how the stats increase now and what the rewards are ?

**Comment by P03W** [comment]
Yep updated, thanks for the reminder
