### ISSUE TITLE
Cow crushers only allow you to feed one cow (MC 1.17.1)

### ISSUE THREAD

**Issue by wizbyt** [P03W/RPGStats#68]
**Describe the bug**
Bit of strange bug here, when you have a fully working cow crusher and you try to breed the cows you can only feed one cow. The mod seems to prevent you from feeding more and breeding them.

**To Reproduce**
1. Build a working cow crusher, breed lots of cows.
2. Apply mod (rpgstats-4.1.6+1.17.1)
3. Wait and try and breed cows with wheat.
4. One one cow can be fed, you can't feed anymore cows

**Expected behavior**
Feed and breed multiple cows.

**Environment**
- [ ] Server
- [X] Client
- [X] Singleplayer
- [ ] Lan Server

**Comment by P03W** [comment]
Do you have a reference for what a cow crusher is? I'm not familiar with that term

**Comment by wizbyt** [comment]
Here's an example of a Cow Crusher

https://www.youtube.com/watch?v=QnH2-vlBU2s

**Comment by P03W** [comment]
Alright thanks

**Comment by wizbyt** [comment]
After a bit of further testing, by removing all mods and reinstalling them, one at a time, it seems to be working as it should, so looks like a false alarm.

I'll keep monitoring in case it happens again and see if I can provide further information, for now it looks resolved.

**Comment by P03W** [comment]
Alright thanks, certainly weird
