### ISSUE TITLE
Impaling doesn't work on other mobs.

### ISSUE THREAD

**Issue by Neubulae** [P03W/RPGStats#69]
It still works as Vanilla. I've done this after altering the MixinPriority to 50.
Fabrications "Bedrock Impaling" works tho, but I disabled it and it still doesn't render RPG's useful.

**Comment by P03W** [comment]
Fixed in 4.1.8, sorry for the delay

**Comment by Neubulae** [comment]
ouf where is da sorse

**Comment by P03W** [comment]
Pushed now, sorry about that, no idea how it didnt get pushed

**Comment by Neubulae** [comment]
this doesn't look fixed on my end... I suppose I'd have to look into mixins if something's been disrupting

**Comment by Neubulae** [comment]
![图片](https://user-images.githubusercontent.com/24774842/128766877-a6bde267-950b-41d5-98ce-51caeef2e579.png)
hm?

**Comment by P03W** [comment]
Possibly, does removing that mod cause the issue to go away?
