### ISSUE TITLE
Feature Suggestion: Add Config to Adjust Defense's Health Gain

### ISSUE THREAD

**Issue by EmoBubbleGum** [P03W/RPGStats#74]
Config to adjust what levels give health for defense:

For some servers, the health might just be too powerful. Especially if the server has other mods that have lowered health as a detriment to certain rpg classes. I'd suggest a section of the config that lets you change how many levels (after 10 of course) it takes to gain a half heart.

As an aside, it might be a good idea to give it a half a second cooldown to gaining exp, simply to make letting multiple enemies smack your shield a little less powerful for leveling.

**Comment by P03W** [comment]
Accidentally merged 2 commits there, 5d718e9 adds both the config scaling and reduces XP gain somewhat
