### ISSUE TITLE
[Feature] Damage Source Blacklist

### ISSUE THREAD

**Issue by red2blue** [P03W/RPGStats#76]
Please create a config option that allows you to blacklist entities / blocks from gaining XP

ie; Lava. if you put down lava in a bucket and just keep going into the lava and heal yourself, you will farm defense xp points fairly fast.

**Comment by P03W** [comment]
This mod is not meant to be completely un-farmable, I'll consider it though

**Comment by red2blue** [comment]
Would be a good option for modpack owners such as myself, just saying :)

**Comment by P03W** [comment]
I mean, I can do my best, but ultimately someone will always find some way

And glad you like it :)

**Comment by P03W** [comment]
added a basic one in 4.2.1, if you have any improvement suggestions feel free to mention them
