### ISSUE TITLE
Lodging

### ISSUE THREAD

**Issue by ImanCraft** [P03W/RPGStats#77]
I would like to feel some sort of progression when it comes to chopping trees. Like at level 25 you have a 10% chance of 2 logs dropping instead of one. Level 50 could be like the same skill just stronger or the ability to chop down trees at root. Idk. I like chopping trees. :)

**Comment by P03W** [comment]
So, as nice as this would be, I really cant add more stats myself at the moment

I've completely run out of ideas for per-level rewards, I still need to rework fishing and mining rewards, and taking up more from those would be frustrating to come up with something more unique

Additionally I feel that would fit better under farming, by maybe thats just me
