### ISSUE TITLE
/rpgstats <player> displays wrong stats

### ISSUE THREAD

**Issue by Katorone** [P03W/RPGStats#8]
The command /rpgstats <otherplayer> will display the stats of the player who runs the command.  This isn't the case when the command is executed from the console.

![image](https://user-images.githubusercontent.com/918422/89109793-bce1ca00-d444-11ea-9d75-dda276ee6d89.png)
![image](https://user-images.githubusercontent.com/918422/89109800-c9feb900-d444-11ea-8b0e-78cd8749b720.png)

**Comment by P03W** [comment]
Oops, that's been broken for a while :/

Should get fixed within a day or 2

**Comment by P03W** [comment]
Should be fixed in 2.1.1

**Comment by Katorone** [comment]
Thanks !
