### ISSUE TITLE
Mod doesn't seem to load into multiplayer server

### ISSUE THREAD

**Issue by andres-urda** [P03W/RPGStats#80]
**Describe the bug**
/rpgstats is not a valid command. "Unknown or incomplete command"

**To Reproduce**
Mod is included in my server's mod folder. I use Forge.

**Screenshots and Logs**
[logs.txt](https://github.com/P03W/RPGStats/files/7447430/logs.txt)

**Environment**
- [X] Server
- [ ] Client
- [ ] Singleplayer
- [ ] Lan Server

**Mod list**
Provide your mod lit here if possible.

![modlist](https://user-images.githubusercontent.com/93447646/139554786-2e4ba5d6-10be-4757-97b7-4ba39890c1ee.png)

**Comment by P03W** [comment]
This is a fabric mod not a forge mod
Forge should have given you some sort of warning about that though
