### ISSUE TITLE
NPE when bonemeal is used

### ISSUE THREAD

**Issue by xxlio109** [P03W/RPGStats#81]
1.17.1 
Player enters the server and immediately crashes 

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/5/21, 6:01 PM
Description: Exception while ticking

java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca.api.v3.component.ComponentProvider.getComponentContainer()" because "provider" is null
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.getInternal(ComponentKey.java:224)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:82)
	at mc.rpgstats.main.RPGStats.getComponentLevel(RPGStats.java:68)
	at net.minecraft.item.BoneMealItem.handler$zna000$groundEffectiveness(BoneMealItem:535)
	at net.minecraft.item.BoneMealItem.useOnGround(BoneMealItem)
	at net.minecraft.class_2357$11.dispenseSilently(class_2357.java:471)
	at net.minecraft.block.dispenser.ItemDispenserBehavior.redirect$cea000$injectNoCostBehavior(ItemDispenserBehavior:521)
	at net.minecraft.block.dispenser.ItemDispenserBehavior.dispense(ItemDispenserBehavior:15)
	at net.minecraft.block.DispenserBlock.dispense(DispenserBlock:90)
	at net.minecraft.block.DispenserBlock.scheduledTick(DispenserBlock:113)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.scheduledTick(AbstractBlock:918)
	at net.minecraft.server.world.ServerWorld.tickBlock(ServerWorld:644)
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.executeTicks(LithiumServerTickScheduler.java:280)
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.tick(LithiumServerTickScheduler.java:93)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:364)
	at net.minecraft.server.MinecraftServer.redirect$dik000$fixUpdateSuppressionCrashTick(MinecraftServer:8784)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:891)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:335)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.MinecraftServer.handler$dbm000$modifiedRunLoop(MinecraftServer:7890)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.getInternal(ComponentKey.java:224)
	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:82)
	at mc.rpgstats.main.RPGStats.getComponentLevel(RPGStats.java:68)
	at net.minecraft.class_1752.handler$zna000$groundEffectiveness(class_1752.java:535)
	at net.minecraft.class_1752.method_7719(class_1752.java)
	at net.minecraft.class_2357$11.method_10135(class_2357.java:471)
	at net.minecraft.class_2347.redirect$cea000$injectNoCostBehavior(class_2347.java:521)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at net.minecraft.class_2315.method_10012(class_2315.java:90)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:918)
	at net.minecraft.class_3218.method_14189(class_3218.java:644)

-- Block being ticked --
Details:
	Block location: World: (-495,68,-746), Section: (at 1,4,6 in -31,4,-47; chunk contains blocks -496,-64,-752 to -481,319,-737), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:520)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:894)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:335)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:831)
	at net.minecraft.server.MinecraftServer.handler$dbm000$modifiedRunLoop(MinecraftServer:7890)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)

-- Affected level --
Details:
	All players: 6 total; [class_3222['zhenxi'/479, l='ServerLevel[world]', x=-416.36, y=64.00, z=-712.20], class_3222['MASK'/618, l='ServerLevel[world]', x=-1362.72, y=129.00, z=1545.51], class_3222['loli_1'/9969, l='ServerLevel[world]', x=415.94, y=98.00, z=2429.22], class_3222['yanjian'/12204, l='ServerLevel[world]', x=245.46, y=61.10, z=-11528.34], class_3222['Joyu_gugu'/11568, l='ServerLevel[world]', x=-409.21, y=66.67, z=-721.69], class_3222['AIPC'/7334, l='ServerLevel[world]', x=-683.50, y=79.56, z=828.50]]
	Chunk stats: 7535
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,76,96), Section: (at 0,12,0 in -8,4,6; chunk contains blocks -128,-64,96 to -113,319,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 76357 game time, 76357 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 59694 (now: false), thunder time: 22581 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$dbm000$modifiedRunLoop(MinecraftServer.java:7890)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 16, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 9955814416 bytes (9494 MiB) / 17179869184 bytes (16384 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 24
	JVM Flags: 2 total; -Xms16G -Xmx16G
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.4.1
		ae2wtlib: AE2WTLib 9.0.0-beta.7
		agape_space: Space Dimensions 0.3.4
		apoli: Apoli 2.0.4
		appleskin: AppleSkin mc1.17-2.1.3
		appliedenergistics2: Applied Energistics 2 9.0.0-beta.1
		aqupdcaracal: Caracal mob 1.17-1.3.2
		arcanus: Arcanus 1.22
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 2.6.35
		artifality: Artifality 0.4.2
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.3
		audiooutput: AudioOutput 0.0.4
		balm-fabric: Balm 1.3.0+0
		battletowers: Battle Towers 3.4.1-1.17.1
		bclib: BCLib 0.3.1
		bedrockwaters: BedrockWaters 1.5.0+1.17.1
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.11.0-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-12
		bitsandchisels: BitsAndChisels 2.5.3
		blast: BLAST 1.8
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.2-1.17.1
		bountiful: Bountiful 1.0.0
		buildinggadgets: st'ructure tools 1.0.1
		calio: Calio 1.0.3
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carpet: Carpet Mod 1.4.51
		carpet-extra: Carpet Extra 1.4.51
		carpet-tis-addition: Carpet TIS Addition 1.23.1+build.703
		carrier: Carrier 1.8.1
		chalk: Chalk 1.0.1
		charm: Charm 3.3.2
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		collective-fabric: Collective (Fabric) 1.61
		colorutility: ColorUtility 2.0.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.12.2
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		companion_bats: Companion Bats 1.18.3
		completeconfig: CompleteConfig 1.0.0
		compress: Compress 'em [v1.5]
		conjuring: Conjuring 1.0.13
		consistency_plus: Consistency Plus 0.4.1+1.17
		cosmetic-armor: Cosmetic Armor 1.1.0
		craftingtweaks: Crafting Tweaks 13.0.0+0
		croptopia: Croptopia 1.6.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta44-1.17
		customportals: Custom Portals 2.1.0
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dimdoors: DimensionalDoors 4.0.0+beta.3-31.10.2021
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 1.0.5
		doom: Doom Fabric 4.0.32
		dragonloot: DragonLoot 1.0.9
		dungeons_arise: When Dungeons Arise 2.1.48-fabric
		ec-core: Essential Commands Core 1.0.0-mc1.17.1
		eldritch_mobs: Eldritch Mobs 1.9.6
		emagnet: E Magnet 1.2.3
		enchant_giver: Enchant Giver 1.1.0
		enhancedcelestials: Enhanced Celestials 2.0.5
		essential_commands: Essential Commands 0.17.0-mc1.17.1
		expandedstorage: Expanded Storage 7.2.7
		extraalchemy: Extra Alchemy 1.6.1
		extragenerators: Extra Generators 1.1-BETA+1.17
		extraorigins: Extra Origins 1.17-8
		fabric: Fabric API 0.41.3+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.1+ffbe6d8f18
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.12+ffbe6d8f18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ef17126d18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.12+81e15a8918
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+81e15a8918
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+ffbe6d8f18
		fabricenchantments: Fabric Enchantments 0.4.2
		fabricloader: Fabric Loader 0.11.7
		fabrictailor: Fabric Tailor 1.7.1
		factory: Factory 1.17.1-1.4.0
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.14.3
		farmersdelight: Farmer's Delight 1.17.1-0.1.2
		fastfurnace: FastFurnace 1.17-3.0
		fatxporbs: Fat Experience Orbs 1.0.1
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		flan: Flan 1.17.1-1.6.2
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.2
		geckolib3: Geckolib 3.0.19
		givemehats: Give Me Hats! 1.6.5
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goat: Goat origin 1.0.0
		gobber2: Gobber2 2.4.56
		goldenhoppers: Golden Hoppers 1.1.0
		golemsgalore: Golems Galore 1.0.3-1.17.1
		guifollowers-fabric: GUI Followers (Fabric) 1.7
		harvest_scythes: Harvest Scythes 2.0.6
		hctm-base: HCTM Base 3.6.2
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		hookshot: Hookshot 22.0
		horseinfo: Horse Info 0.3.0-1.17
		horsestonks: Horse Stonks 1.0.0
		hydrogen: Hydrogen 0.3
		iceberg: Iceberg 1.0.23
		impersonate: Impersonate 2.3.5
		incantationem: Incantationem 1.1.2+1.17.1
		incubus_core: Incubus Core 1.6.1
		indrev: Industrial Revolution 1.11.0-alpha.4
		inmis: Inmis 2.3.2-1.17.1
		ironfurnaces: Iron Furnaces 1.17.1-2.6.1-fabric
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		justenoughkeys: Just Enough Keys 0.3.2
		kambrik: Kambrik 1.1.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.3-BETA+1.17
		kjsextras: KubeJS Extras 1.4.0
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		kyrptconfig: Kyrpt Config 1.2.1-1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.9.2
		libblockattributes_core: LibBlockAttributes (Core) 0.9.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.2
		libblockattributes_items: LibBlockAttributes (Items) 0.9.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.3.9.2
		lightestlamp: Lightest Lamps 0.9.3
		lithium: Lithium 0.7.4
		lootcrates: Modular Loot Crates 2.1.1
		lovely_snails: Lovely Snails 1.0.3+1.17
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		magicfungi: Magic Fungi 0.5.0-BETA+1.17.1
		magna: Magna 0.4.0-1.17.1
		matrix: Matrix 1.0.0
		maybe-data: Maybe data 1.0.1-1.17
		mcda: MC Dungeons Armors 1.7.15
		mcdw: MC Dungeons Weapons 3.5.6
		mcsa: MC Story Mode Armor 2.3.2-1.17
		megane: megane 5.5.0
		megane-applied-energistics-2: megane-applied-energistics-2 5.5.0+9.0.0-alpha.2
		megane-base: megane-base 5.5.0
		megane-dml-simulacrum: megane-dml-simulacrum 5.5.0+1.0.5
		megane-extra-generators: megane-extra-generators 5.5.0+1.1-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.5.0+1.3.0-fc40aa9d18
		megane-industrial-revolution: megane-industrial-revolution 5.5.0+1.11.0-alpha.1
		megane-kibe: megane-kibe 5.5.0+1.9.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.5.0+0.9.0
		megane-reborn-core: megane-reborn-core 5.5.0+5.0.8-beta-build.111
		megane-runtime: megane-runtime 5.5.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.5.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.5.0+5.0.8-beta-build.111
		megane-vanilla: megane-vanilla 5.5.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.5.0+1.3.0
		minecraft: Minecraft 1.17.1
		minershorizon: Miner's Horizon 1.7.2-1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		moretags: More Tags 1.2.5
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		myron: Myron 1.6.1
		mythic-mounts: Mythic Mounts 1.17.1-2.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.4
		notenoughcrashes: Not Enough Crashes 3.7.1+1.17.1
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		openloader: OpenLoader 3.0.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.1.3
		origins-classes: Origins: Classes 1.2.2
		owo: oωo 0.3.0
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		pipe: Pipe 1.6.0
		placeholder-api: Placeholder API 1.1.1+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.8+1.17.1
		polymorph: Polymorph 0.0.14-1.17.1
		prefab: Prefab 2.1.6
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industial Quarry Mod 0.5.1
		quickshulker: Quick Shulker 1.3.1-1.17
		ratsmischief: Rat's Mischief 1.2.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.10-beta
		redbits: Red Bits 1.10.1
		repurposed_structures: Repurposed Structures 2.5.1+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		resourceful_tools: Resourceful Tools 1.1.21
		respawnablepets: Respawnable Pets 1.17-5
		rhino: Rhino 1701.1.5-build.71
		roughlyenoughitems: Roughly Enough Items 6.1.314-alpha
		rpgstats: RPGStats 4.2.1+1.17.1
		rswires: RSWires 4.11.2
		schmucks: Schmucks 1.4.0
		secretrooms: Secret Rooms 1.1.0+1.17
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		server_translations_api: Server Translations API 1.4.6+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.3+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		simplegrinder: Simple Grinder 17.0.1-Fabric
		somnus: Somnus API 0.0.14-1.17.1
		soulbound: Soulbound 2.0.0
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 1.1.0
		storagecabinet: Storage Cabinet 1.4.1
		structure-helpers: Structure Helpers 3.2.0
		structurized: Structurized 1.3.0
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.10-beta
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 1.6.1
		the_aether: The Aether Reborn 1.17.1-1.6.0
		things: Things 0.2.6
		toms_storage: Tom's Simple Storage Mod 1.1.18
		transportables: Transportables 1.0.6
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		universal-graves: Universal Graves 1.1.3+1.17.1
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.17
		valley: ValleyCraft 1.3.2
		veinmining: Vein Mining 0.0.10-1.17
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		ward_blocks: Ward Blocks 1.1.9
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.1.2
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.3.1
		wthit: wthit 3.10.1
		xaerominimap: Xaero's Minimap 21.20.0
		xaeroworldmap: Xaero's World Map 1.18.1
		xlpackets: XLPackets 2.0-1.17
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-19
		zihlaunchpads: ZIHLaunchpads 1.1.1
	Player Count: 6 / 50; [class_3222['zhenxi'/479, l='ServerLevel[world]', x=-416.36, y=64.00, z=-712.20], class_3222['MASK'/618, l='ServerLevel[world]', x=-1362.72, y=129.00, z=1545.51], class_3222['loli_1'/9969, l='ServerLevel[world]', x=415.94, y=98.00, z=2429.22], class_3222['Joyu_gugu'/11568, l='ServerLevel[world]', x=-409.21, y=66.67, z=-721.69], class_3222['yanjian'/12204, l='ServerLevel[world]', x=245.46, y=61.10, z=-11528.34], class_3222['AIPC'/7334, l='ServerLevel[world]', x=-683.50, y=79.56, z=828.50]]
	Data Packs: vanilla, Fabric Mods, dimdoors/classic, dimdoors/default, file/Repurposed_Structures-Better_Strongholds_Fabric_Beta.zip, file/Repurposed_Structures-Charm.zip, file/Repurposed_Structures-Farmers_Delight_Fabric.zip, file/Repurposed_Structures-More_Villagers_Fabric.zip, file/doom, file/eldritch_mobs, file/givemehats, file/nophantom, openloader/data/Repurposed_Structures-Charm.zip, openloader/data/givemehats, secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: None`

**Comment by P03W** [comment]
Please use the bug report template in the future
