### ISSUE TITLE
Critical performance issue.

### ISSUE THREAD

**Issue by Nayrin** [P03W/RPGStats#86]
Whenever I try to break a block the framerate starts going down to 0, I looked up what was happening in the server console and identified a few lines spamming when trying to breaking a block:

</log4j:Event>
  <log4j:Event logger="net.minecraft.class_2983" timestamp="1639660344897" level="INFO" thread="Server thread">
    <log4j:Message><![CDATA[[STDOUT]: Was 0.2 is now 0.2]]></log4j:Message>

This causes the game to freeze for a few seconds and sometimes crash. Since I have a bunch of mods running at the same time I've spent some time running them one by one to make sure the problem was being caused by RPGStats.

https://user-images.githubusercontent.com/48848212/146397496-6261f205-f5f7-4e4c-b502-1778e078821c.mp4

My PC specs:
- Processor: AMD Ryzen 3 3200G with Radeon Vega 8 integrated graphics.
- Memory: 2x4 8GB 2666MHz RAM.
- Storage: 120GB 6GB/s SATA SSD with read speed up to 500MB/s and write speed up to 380MB/s (~40GB space available).
- Page file: 14,070MB managed by system.
- Default processes running in background plus a chromium browser and WhatsApp.

**Comment by P03W** [comment]
This was fixed yesterday, update the mod
