### ISSUE TITLE
Mods that would be nice if they were connected to their tools.

### ISSUE THREAD

**Issue by ColdDead** [P03W/RPGStats#90]
It would be nice if the following mods are made compatible. You can also use the tools lvl to run the rpg system.
Mods:
Harvest Scythes 
Artifality

**Comment by P03W** [comment]
Harvest scythes already has compat?

**Comment by ColdDead** [comment]
I use the harvest scythes and i get not xp for the harvesting

**Comment by P03W** [comment]
Could you enable the debug xp log and share that?

**Comment by ColdDead** [comment]
Can i client side enable it? Is a public server

**Comment by P03W** [comment]
No the server does absolutely everything

**Comment by P03W** [comment]
Found the bug with harvest scythes, ill fix that

**Comment by P03W** [comment]
What exactly should get compat with Artifality? I don't see anything obvious on their wiki

**Comment by ColdDead** [comment]
They have tools for example the scythe with which you can boost plants with bone meal + harvest you still get a bit of xp but no rpg lvl even though you harvest the plant

**Comment by Kluzzio** [comment]
https://github.com/PinkGoosik/artifality/blob/1.18-fabric/src/main/java/artifality/item/HarvestStaffItem.java#L39 Artifality is slightly lazy with how this part is implemented. If this one part was changed to handle the breaking of the crop similarly to how SimpleHarvest is done, a simple mixin could handle the functionality here.

**Comment by Kluzzio** [comment]
RPGStats currently does make an exception for SimpleHarvest but the point is that the implementation in artifality should not be completely devoid of reference to the player in the replanting of the crop.

**Comment by Kluzzio** [comment]
Artifality compat is now implemented
