### ISSUE TITLE
Fall Damage with armor

### ISSUE THREAD

**Issue by PassyFox** [P03W/RPGStats#91]
**Describe the bug**
is it possible that fall damage shouldn't give defense xp when a person has feather falling 4 and protection 4, right now users are working the system and the even set up a beacon so they heal fast enough and keep falling in a redstone contraption to gather XP

**To Reproduce**
fall from any hight that gives damage

**Expected behavior**
i didn't expected to have fall damage give xp when a player has damage reduction armor on, maybe put fall damage in the config list as an option to prevent it from gaining xp?

**Environment**
- [ x ] Server

**Mod list**
Fabric Api
RPGstats

**Comment by P03W** [comment]
I'll add it to the damage blacklist config

Probably with all the others, forgot enchants could affect stuff that bypasses armor

**Comment by PassyFox** [comment]
yeah enchants are a bitch sometimes ;P
thenx for the fast reply, will see the update when ya post it then :)
