### ISSUE TITLE
Ticking entity conflict with MC Dungeons Armors | 1.18.1

### ISSUE THREAD

**Issue by switchnlade** [P03W/RPGStats#92]
**Describe the bug**
While having RPGStats downloaded with MC Dungeons Armors, a ticking entity crash occurs when a wandering trader drinks an invisibility potion. It occurs on the latest versions of both, and related to net.minecraft.class_1812. This one looks different than the previous issue reports however so probably not the exact same as those mixin crashes.

**To Reproduce**
1. Have all mods from mod list installed
2. Spawn in a Wandering trader
3. Set time to night
4. Watch trader drink invisibility potion
5. Crash occurs

**Expected behavior**
Upon finishing the potion, the trader will turn invisible instead of becoming a ticking entity.

**Screenshots and Logs**
Crash report: https://pastebin.com/fSfUXjhe

**Environment**
- Server (crashed)
- Singleplayer (crashed)

**Mod list**
Cloth Config API (Fabric) v6.1.48
Fabric API v0.45.2
MC Dungeons Armors v1.9.0
RPGStats v4.3.3

**Comment by P03W** [comment]
> Upon finishing the potion, the trader will turn invisible instead of becoming a ticking entity.

I mean the wandering trader is already a "ticking entity", all entities tick. Semantically this should be "instead of crashing the game"

But yes I'll get on this

**Comment by switchnlade** [comment]
My bad on not being correct on that bit, I haven't quite looked into modding yet so don't fully know the workings behind it, thanks for acting on the issue.

**Comment by P03W** [comment]
Yeah its not an issue I knew what you meant

**Comment by P03W** [comment]
Well, this is a *very* nasty bug, almost seems like a mixin issue, Ill see what I can do but this seems really fragile

**Comment by switchnlade** [comment]
Hey, sorry to add on more, but just want to make sure on something here. The crash also occurs whenever a potion is drank by the player. Here's the log from that crash: https://pastebin.com/ADwsReiE. Hopefully it's just the same issue as it seems. Since it is a different cause however, I want to include it on the possibility it's not the same issue and is another one.
