### ISSUE TITLE
 Right-Click-Harvest not counting XP

### ISSUE THREAD

**Issue by WestphalJonas** [P03W/RPGStats#93]
Is it possible to make RPGStats compatible with Right-Click-Harvest: https://github.com/koelle25/Right-Click-Harvest

Thanks in advance!

**Comment by P03W** [comment]
Is there any advantage to that harvest mod over https://www.curseforge.com/minecraft/mc-mods/simplerharvest which already had compat?

**Comment by WestphalJonas** [comment]
Gonna switch to that version, thank you
