### ISSUE TITLE
[Major Bug] Defense bonus health infinitely stacking

### ISSUE THREAD

**Issue by Master-64** [P03W/RPGStats#97]
**Describe the bug**
Once you defeat the ender dragon, she activates an end portal to allow the player to escape to the overworld. As it turns out for some odd reason, when you have any sort of RPGStat bonus, all of those stats get re-applied for each exit.

**To Reproduce**
1. Gain enough RPGStat experience in any skill to see the glitch easily (preferred to level defense, mining or strength)
2. Locate a stronghold
3. Enter the end
4. Defeat the ender dragon
5. Exit to the overworld
6. All of your RPGStats will stack again

**Expected behavior**
Your RPGStats should never stack

**Screenshots and Logs**
Not applicable.

**Environment**
Singleplayer

**Mod list**
Only mod used was RPGStats.

**Additional Info**
Running on Fabric 0.13.3, Minecraft version 1.18.1.

**Comment by P03W** [comment]
*sigh* THERES NO WINNING WITH THIS BUG D:

Thanks for this, ill try to fix this, ect.

God this is like the 7th time ive had to fix this, damn you mojang

**Comment by Master-64** [comment]
> _sigh_ THERES NO WINNING WITH THIS BUG D:
> 
> Thanks for this, ill try to fix this, ect.
> 
> God this is like the 7th time ive had to fix this, damn you mojang

Hope you can figure it out! I was super confused when I was randomly getting a lot of HP and attack damage all of a sudden, but it also applies to all other stats (not just that one). I'll keep this open in the meantime.

**Comment by P03W** [comment]
Yeah basically its really hard to fix https://bugs.mojang.com/browse/MC-179940 apparently

**Comment by P03W** [comment]
hmmmm I cant actually reproduce this :shipit: 

Is this still a bug in the 1.18.2 version and/or could you send a video?

**Comment by P03W** [comment]
hey @Master-64 if you could get back to me on this somewhat soon that would be great 👍
