### ISSUE TITLE
Ability to infinitely farm MINING xp with silk touch

### ISSUE THREAD

**Issue by haventhadadonutyet** [P03W/RPGStats#98]
**Describe the bug**
if you break and place an ore block with a silk touch pickaxe you can infinitely gain mining xp.

**To Reproduce**
1. Get a silk pickaxe
2. Get an ore block
3. Break ore block with silk pickaxe
4. Place, and repeat

**Expected behavior**
Not to gain xp, similar to mcmmo mining, im not sure how it detects placed blocks though.

**Screenshots and Logs**
not needed

**Environment**
- [ ] Server

**Comment by P03W** [comment]
Added an option to at least partially mitigate this in 4.3.7
