### ISSUE TITLE
Console spam when using the latest version

### ISSUE THREAD

**Issue by Regular-Baf** [P03W/RPGStats#99]
**Describe the bug**
[Server thread/INFO] : [STDOUT] : {}
prints seemingly with no end into the terminal
**To Reproduce**
Try using the mod on a standard Fabric 1.18.2 server. It doesn't seem to matter what mods I have or don't have as the issue occurred when only using Fabric API.

**Environment**
- Server

**Comment by P03W** [comment]
Whoops, thanks, I'll get that out soon

**Comment by P03W** [comment]
Fixed
